version: "3"
services:
  telegram-notifier:
    build: .
    ports:
      - 5002:5000
    env_file:
      - ./.env
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      default:
        ipv4_address: 172.18.2.162
  redis:
    image: redis:alpine
    volumes:
      - ./redis/data:/data
      - ./redis:/usr/local/etc/redis
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.2.163
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.2.160/29
          gateway: 172.18.2.161